FROM eclipse-temurin:21-jdk-ubi9-minimal

# Install X11 and font libraries
RUN microdnf update -y && \
    microdnf install -y \
      libX11 \
      libXext \
      libXi \
      libXrender \
      libXtst \
      fontconfig \
      freetype \
      xauth \
    && microdnf clean all

WORKDIR /workspace
COPY src ./src

RUN mkdir -p out \
    && javac -d out src/stone/*.java src/chap3/*.java

ENTRYPOINT ["java", "-cp", "out"]
CMD ["chap3.LexerRunnerConsole"]
